services:
  frontend:
    build: .
    container_name: react_airbnb
    ports:
      - "5173:5173"
    volumes:
      # Συνδέει τον τωρινό σου φάκελο με τον φάκελο /app του container.
      # Έτσι, ό,τι κώδικα γράφεις στο VS Code, θα ανανεώνεται κατευθείαν στον browser.
      - .:/app
      # Προστατεύει τον φάκελο node_modules του container από το να διαγραφεί
      # ή να αντικατασταθεί από τον τοπικό σου φάκελο.
      - /app/node_modules
    environment:
      # Ειδικά αν δουλεύεις τον κώδικα μέσα από WSL, αυτή η ρύθμιση είναι σωτήρια 
      # γιατί αναγκάζει το σύστημα να ελέγχει σωστά πότε αποθηκεύεις ένα αρχείο 
      # ώστε να κάνει το αυτόματο refresh.
      - CHOKIDAR_USEPOLLING=true